name = "TopOpt"
uuid = "53a1e1a5-51bb-58a9-8a02-02056cc81109"
authors = ["mohamed82008 <mohamed82008@gmail.com>"]
version = "0.4.2"

[deps]
CatViews = "81a5f4ea-a946-549a-aa7e-2a7f63a27d31"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Einsum = "b7d42ee7-0b51-5a75-98ca-779d3107e4c0"
Ferrite = "c061ca5d-56c9-439f-9c0e-210fe06d3992"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
FiniteDifferences = "26cc04aa-876d-5657-8c51-4c34ba976000"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
GeometryTypes = "4d00f742-c7ba-57c2-abde-4428a4b178cb"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Juno = "e5e0dc1b-0480-54bc-9374-aad01c23163d"
LazyArrays = "5078a376-72f3-5289-bfd5-ec5146d43c02"
LineSearches = "d3d80556-e9d4-5f37-9878-2ab0fcc64255"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
MappedArrays = "dbb5928d-eab1-5f90-85c2-b9b0edb7c900"
Nonconvex = "01bcebdf-4d21-426d-b5c4-6132c1619978"
NonconvexIpopt = "bf347577-a06d-49ad-a669-8c0e005493b8"
NonconvexMMA = "d3d89cbb-4ecd-4604-818d-8d1ff343e4da"
NonconvexPercival = "4296f080-e499-44ba-a02c-ae40015c44d5"
NonconvexSemidefinite = "9e21ff56-eb25-42d3-b86f-5b0612f555e7"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Percival = "01435c0c-c90d-11e9-3788-63660f8fbccc"
Preconditioners = "af69fa37-3177-5a40-98ee-561f696e4fcd"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
Tensors = "48a634ad-e948-5137-8d70-aa71f2a747f4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
VTKDataTypes = "10d27dd1-1d0f-5a4c-b178-bd2d0045a217"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
CatViews = "1"
ChainRulesCore = "1"
Distributions = "0.24, 0.25"
Einsum = "0.4"
Ferrite = "=0.3.0"
FillArrays = "0.11"
ForwardDiff = "0.10"
GeometryBasics = "0.3"
GeometryTypes = "0.8"
IterativeSolvers = "0.9"
JSON = "0.21"
Juno = "0.8"
LazyArrays = "0.21"
LineSearches = "7"
MacroTools = "0.5"
MappedArrays = "0.1, 0.2, 0.3, 0.4"
Nonconvex = "1"
Optim = "1.3"
Parameters = "0.12"
Preconditioners = "0.3"
Reexport = "1"
Requires = "1.1"
Revise = "3"
Setfield = "0.7"
StaticArrays = "1"
StatsBase = "0.33"
StatsFuns = "0.9"
StructArrays = "0.5"
Tensors = "1.4"
TimerOutputs = "0.5"
VTKDataTypes = "0.1"
WriteVTK = "1.9"
Zygote = "0.6"
julia = "1.5, 1.6"
